source 'https://rubygems.org'
gem 'faraday', '~> 2.7', '>= 2.7.11'
gem 'faraday-retry'
gem "jekyll", "~> 4.2"
gem 'rmagick', '>=4.2.3'
group :jekyll_plugins do
    gem "jekyll-include-cache" 
    gem 'jekyll-archives'
    gem 'jekyll-diagrams'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed'
    gem 'jekyll-github-metadata'
    gem 'jekyll-imagemagick'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-sitemap'
    gem 'jekyll-target-blank'
    gem 'jekyll-twitter-plugin'
    gem 'unicode_utils'
    #gem 'webrick'
    gem 'htmlcompressor'
    gem 'htmlbeautifier'
    #gem 'rmagick'
    gem 'jekyll-responsive-image'
end
